### ISSUE TITLE
 Some visual assets missing in 1.2.6 release

### ISSUE THREAD

**Issue by jonasjj** [WhitewaterFoundry/Pengwin#498] opened 2019-07-28 05:04 UTC
The icon in the taskbar is blank when Pengwin is running and when pinned to the taskbar. The icon in the start menu is showing.

I have tried reinstalling the app along with some other things like deleting the Windows icon cache and restarting.

**Pengwin Version**
1.2.6.0

**Windows Build**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 2.11.0, 14.03.2019

**Comment by kerbe** [comment] 2019-07-28 05:32
I have this same issue, appeared today after I rebooted my computer (last reboot before this was on Wednesday). Pinned icon in taskbar is invisible, pin itself is still there.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 0703, 21.10.2011
Pengwin version 1.2.6.0

**Comment by hanubeki** [comment] 2019-07-28 12:38
![image](https://user-images.githubusercontent.com/6897531/62006752-ef951a80-b17f-11e9-9055-f039338b8fb7.png)
Icon is gone from my start menu.

```
OS 名:                  Microsoft Windows 10 Home
OS バージョン:          10.0.18362 N/A ビルド 18362
OS 製造元:              Microsoft Corporation
OS 構成:                スタンドアロン ワークステーション
OS ビルドの種類:        Multiprocessor Free
BIOS バージョン:        American Megatrends Inc. 4.6.5, 2012/03/05
```

**Comment by sirredbeard** [comment] 2019-07-28 13:24
Some visual assets are missing in 1.2.6. Depending on your resolution, the icon may be missing in the Start Menu or Taskbar.

I have traced the issue to a bug in Visual Studio 2019 that does not properly bundle some visual assets when the application is built in a folder that is being backed up by OneDrive with Files On Demand enabled, even if 'Always keep on this device is enabled.'

The workaround is to move the build folder and assets to a non-OneDrive folder and build there.

A new build with all visual assets included has been submitted to the store currently and should go out within 24 hours.

I apologize for any inconvenience.

**Comment by sirredbeard** [comment] 2019-07-28 13:55
Here is some additional detail.

Visual assets are provided by the Pengwin UWP wrapper, not the Linux image. This is why this problem occurred with the 1.2.6 update through the Microsoft Store and not an update of pengwin-setup or pengwin-base in the Linux environment.

The Pengwin app is built on a drive backed up by OneDrive with 'Always keep on this device' enabled so that files and assets and assets are not moved into the cloud by the Files On Demand feature.

This was not an issue when we were building with Visual Studio 2017.

This is a normal build log:

```
1>------ Build started: Project: launcher, Configuration: Release ARM64 ------
1>Compiling Messages...
1>MC: Compiling C:\Users\Hayden\Downloads\Pengwin\DistroLauncher\messages.mc
1>stdafx.cpp
1>DistributionInfo.cpp
1>Helpers.cpp
1>DistroLauncher.cpp
1>WslApiLoader.cpp
1>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification
1>Generating code
1>Finished generating code
1>DistroLauncher.vcxproj -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\launcher.exe
1>Done building project "DistroLauncher.vcxproj".
2>------ Build started: Project: DistroLauncher-Appx, Configuration: Release ARM64 ------
2>Copy C:\Users\Hayden\Downloads\Pengwin\\ARM64\Release\launcher.exe into C:\Users\Hayden\Downloads\Pengwin\\ARM64\Release\DistroLauncher-Appx\Pengwin.exe
2>        1 file(s) copied.
2>MyDistro.appxmanifest(14,6): warning APPX0006: This project uses the 'runFullTrust' capability. You should use the Windows Application Packaging Project to produce the store and sideload packages. See https://go.microsoft.com/fwlink/?linkid=871803 for more information.
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_ARM64.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_scale-100.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_scale-125.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_scale-150.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_scale-400.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_1.2.7.0_scale-100.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_1.2.7.0_scale-125.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_1.2.7.0_scale-150.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\Pengwin\ARM64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_1.2.7.0_scale-400.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\DistroLauncher-Appx_1.2.7.0_Test\DistroLauncher-Appx_1.2.7.0_x64_arm64.appxbundle
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\DistroLauncher-Appx_1.2.7.0_x64_arm64_bundle.appxupload
2>Your package has been successfully created.
2>Done building project "DistroLauncher-Appx.vcxproj".
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
A package has been successfully built for Release (x64).
A package has been successfully built for Release (ARM64).
========== Package: 2 succeeded, 0 failed ===========
An app bundle has been successfully built for Release (x64), Release (ARM64).
========== App Bundle: 1 succeeded, 0 failed ===========
```

This is a build log that occurs when you have visual assets stored in a folder backed up by OneDrive as described above:

```
1>------ Build started: Project: launcher, Configuration: Release ARM64 ------
1>Compiling Messages...
1>MC: Compiling C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\DistroLauncher\messages.mc
1>stdafx.cpp
1>DistributionInfo.cpp
1>DistroLauncher.cpp
1>Helpers.cpp
1>WslApiLoader.cpp
1>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification
1>Generating code
1>Finished generating code
1>DistroLauncher.vcxproj -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\launcher.exe
1>Done building project "DistroLauncher.vcxproj".
2>------ Build started: Project: DistroLauncher-Appx, Configuration: Release ARM64 ------
2>Copy C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\\ARM64\Release\launcher.exe into C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\\ARM64\Release\DistroLauncher-Appx\Pengwin.exe
2>        1 file(s) copied.
2>MyDistro.appxmanifest(14,6): warning APPX0006: This project uses the 'runFullTrust' capability. You should use the Windows Application Packaging Project to produce the store and sideload packages. See https://go.microsoft.com/fwlink/?linkid=871803 for more information.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\install.tar.gz.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\LargeTile.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\LargeTile.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\LargeTile.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\LargeTile.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\LargeTile.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SmallTile.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SmallTile.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SmallTile.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SmallTile.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SmallTile.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SplashScreen.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SplashScreen.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SplashScreen.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SplashScreen.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\SplashScreen.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square150x150Logo.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square150x150Logo.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square150x150Logo.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square150x150Logo.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square150x150Logo.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.altform-unplated_targetsize-16.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.altform-unplated_targetsize-256.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.altform-unplated_targetsize-32.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.altform-unplated_targetsize-48.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.targetsize-16.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.targetsize-24.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.targetsize-24_altform-unplated.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.targetsize-256.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.targetsize-32.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Square44x44Logo.targetsize-48.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\StoreLogo.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\StoreLogo.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\StoreLogo.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\StoreLogo.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\StoreLogo.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Wide310x150Logo.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Wide310x150Logo.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Wide310x150Logo.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Wide310x150Logo.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageLayout\Assets\Wide310x150Logo.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\install.tar.gz.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\LargeTile.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\LargeTile.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\LargeTile.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\LargeTile.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\LargeTile.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SmallTile.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SmallTile.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SmallTile.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SmallTile.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SmallTile.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SplashScreen.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SplashScreen.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SplashScreen.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SplashScreen.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\SplashScreen.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square150x150Logo.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square150x150Logo.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square150x150Logo.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square150x150Logo.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square150x150Logo.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.altform-unplated_targetsize-16.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.altform-unplated_targetsize-256.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.altform-unplated_targetsize-32.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.altform-unplated_targetsize-48.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.targetsize-16.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.targetsize-24.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.targetsize-24_altform-unplated.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.targetsize-256.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.targetsize-32.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Square44x44Logo.targetsize-48.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\StoreLogo.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\StoreLogo.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\StoreLogo.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\StoreLogo.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\StoreLogo.scale-400.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Wide310x150Logo.scale-100.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Wide310x150Logo.scale-125.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Wide310x150Logo.scale-150.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Wide310x150Logo.scale-200.png.
2>GENERATEPROJECTPRIFILE : warning PRI298: 0xdef00535 - File or folder ignored due to file attributes (hidden, system, link): ARM64\Release\PackageUploadLayout\Assets\Wide310x150Logo.scale-400.png.
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_ARM64.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_scale-100.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_scale-125.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_scale-150.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\DistroLauncher-Appx_1.2.7.0_scale-400.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_1.2.7.0_scale-100.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_1.2.7.0_scale-125.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_1.2.7.0_scale-150.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\OneDrive\Documents\GitHub\Pengwin\ARM64\Release\DistroLauncher-Appx\Upload\DistroLauncher-Appx_1.2.7.0_scale-400.appx
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\DistroLauncher-Appx_1.2.7.0_Test\DistroLauncher-Appx_1.2.7.0_x64_arm64.appxbundle
2>DistroLauncher-Appx -> C:\Users\Hayden\Downloads\DistroLauncher-Appx_1.2.7.0_x64_arm64_bundle.appxupload
2>Your package has been successfully created.
2>Done building project "DistroLauncher-Appx.vcxproj".
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
A package has been successfully built for Release (x64).
A package has been successfully built for Release (ARM64).
========== Package: 2 succeeded, 0 failed ===========
An app bundle has been successfully built for Release (x64), Release (ARM64).
========== App Bundle: 1 succeeded, 0 failed ===========
```

You can see that Visual Studio 2019 does not properly bundle all the visual assets from a OneDrive folders, even though they are there, generating several "warning PRI298: 0xdef00535".

Furthermore, these errors are moved off the screen when the build is complete, with no indication of anything is amiss.

This causes some users on some display resolutions to go without an icon.

The remediation we will take going forward is:

1. Review all build logs manually before submitting a build.
2. Move building off a OneDrive-backed up folder until the issue is fixed by Microsoft, either in OneDrive or Visual Studio 2019.
3. Eventually we will be moving to a cloud build system which will automate builds and notify us of build error messages such as above. We have been exploring Azure Pipelines for this since some of the team received training at Build.

**Comment by sirredbeard** [comment] 2019-07-28 14:11
A detailed report has been submitted to Microsoft via Feedback Hub: https://aka.ms/AA5qu32

**Comment by hanubeki** [comment] 2019-07-28 14:16
![image](https://user-images.githubusercontent.com/6897531/62007870-89af8f80-b18d-11e9-8f49-ab24de2c081a.png)
I've received `1.2.7.0` update and the issue is fixed.

**Closed** 2019-08-09 22:55 UTC
Labels: Bug, Implemented, Patched
