### ISSUE TITLE
Fresh install of Pengwin Hangs on 20H1 with WSL2 enabled

### ISSUE THREAD

**Issue by bushidocodes** [WhitewaterFoundry/Pengwin#516] opened 2019-08-19 18:01 UTC
**Describe the bug**

During initial installation, Pengwin hangs after setting the username and password and never gets to a usable shell unless the user presses Control+C. This behavior then occurs whenever Pengwin is launched.

If I revert to WSL1, then the shell loads as expected.

**To Reproduce**
I removed my existing WSL and Pengwin install completely, moved to the Fast Ring, followed instructions to configure WSL2, set WSL2 as the system default, installed Pengwin, noted that Pengwin was running as WSL2, launched to see the aforementioned hang behavior on launch

**Expected behavior**
I expect my shell to launch as normal. 

**Screenshots**

Hangs on launch
![image](https://user-images.githubusercontent.com/8700322/63287546-9608a300-c288-11e9-9f81-9ad0e523b15b.png)

Ctrl+C to get to a shell after waiting for minutes
![image](https://user-images.githubusercontent.com/8700322/63287781-36f75e00-c289-11e9-8a3e-6d19cccf9c51.png)

Showing that WSL2 is enabled.
![image](https://user-images.githubusercontent.com/8700322/63287742-221aca80-c289-11e9-96c2-13dd4d5d62af.png)

Hangs on initial setup like so
![image](https://user-images.githubusercontent.com/8700322/63288369-8427ff80-c28a-11e9-9f82-a29c33efdb3e.png)

**Additional context**

**Basic Troubleshooting Checklist**

[X] I have searched Google for the error message.
[X] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[X] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[X] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[X] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[X] I have disabled and re-enabled WSL in Windows Features.
[X] I have run Windows 10 updates and restarted.

What other troubleshooting have you attempted?

Insert here:

**Pengwin Version**

Find: Settings->Apps->Apps & features->Pengwin->Advanced Options->Version.

Insert here: 1.2.7.0

**Windows Build**

Run 'systeminfo | findstr /C:"OS"' in Command Prompt and insert here:
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.18963 N/A Build 18963
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. F12, 5/15/2014

For help on retrieving: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#check-your-build-number

**Comment by sirredbeard** [comment] 2019-08-19 18:26
Thanks for the report but closing as duplicate of #497.

This is an upstream issue in some builds of Windows Insider, see https://github.com/microsoft/WSL/issues/4337.

It breaks some of the unique interop stuff we do between the Linux and Windows environment on Pengwin.

We recommend known good build 18941.

**Closed** 2019-08-19 18:26 UTC
