### ISSUE TITLE
sudo su - gives errors

### ISSUE THREAD

**Issue by kerbe** [WhitewaterFoundry/Pengwin#403] opened 2019-04-12 01:05 UTC
**Describe the bug**
When getting root privileges with command `sudo su -` following errors are produced:

    ~$ sudo su -
    wslpath: /usr/local/bin/cmd-exe: line 5: cmd.exe: command not found: Invalid argument
    ln: failed to create symbolic link '/root/winhome' -> '': No such file or directory

Everything however feels like working. These errors didn't happen prior Pegwin 1.2.3.0 update.

**To Reproduce**
1. Open Pegwin 1.2.3.0
2. Type `sudo su -`
3. Give your password for sudo, and see those errors.

**Expected behavior**
Root privileges without any extra messages.

**Basic Troubleshooting Checklist**

[x] I have searched Google for the error message.
[ ] I have checked official WSL troubleshooting documentation: https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#confirm-wsl-is-enabled.
[ ] I have searched the official Microsoft WSL issues page: https://github.com/Microsoft/WSL/issues.
[x] I have searched the Pengwin issues page: https://github.com/WhitewaterFoundry/Pengwin/issues.
[ ] I have reset Pengwin: Settings->Apps->Apps & features->Pengwin->Advanced Options->Reset. 
[ ] I have disabled and re-enabled WSL in Windows Features.
[x] I have run Windows 10 updates and restarted.

**Pengwin Version**
`Pegwin 1.2.3.0`

**Windows Build**

    OS Name:                   Microsoft Windows 10 Pro
    OS Version:                10.0.17763 N/A Build 17763
    OS Manufacturer:           Microsoft Corporation
    OS Configuration:          Standalone Workstation
    OS Build Type:             Multiprocessor Free
    BIOS Version:              American Megatrends Inc. 0703, 21.10.2011

**Comment by crramirez** [comment] 2019-04-12 04:14
Ok it looks like this is the same issue as MySQL. We will release a fix for it soon.

**Comment by sirredbeard** [comment] 2019-04-12 13:43
@crramirez You suspect this is the same issue as #394?

**Comment by crramirez** [comment] 2019-04-12 13:51
Yes. The scripts in /etc/profile must take into account the login of other users besides the default one. We can check for any group or if cmd.exe is reachable or not. Only the default user has a Windows path. Unless that the environment be explicitly passed with su.

**Comment by WSLUser** [comment] 2019-04-12 14:23
I have this issue as well

**Comment by sirredbeard** [comment] 2019-04-12 15:35
Closing as duplicate of #394.

**Closed by sirredbeard** 2019-04-12 15:35 UTC
Labels: Triage

**Comment by crramirez** [comment] 2019-04-12 16:03
What is strange in this case is that `sudo -s` is executing `/etc/profile`. It doesn't happen to me.

**Comment by WSLUser** [comment] 2019-04-12 16:13
So after I close the terminal and start again, the issue reappears. Very strange.

**Comment by WSLUser** [comment] 2019-04-12 16:13
I also noticed all the Windows paths were gone, leaving only Linux paths that were added from the installs done by pengwin-setup.

**Comment by crramirez** [comment] 2019-04-12 16:14
I will insert this

```
# Check if we have Windows Path
if ( ! which cmd.exe ); then
  exit 0
fi

```

into "/etc/profile.d/00-pengwin.sh" and any other script that needs Windows Path. Including pengwin-setup which cannot be run with another user but the default one.

**Comment by crramirez** [comment] 2019-04-12 16:15
Yes @WSLUser Windows Path disappear for root unless you run it with sudo -E

**Comment by WSLUser** [comment] 2019-04-12 16:18
May be worth bringing up as another issue but WSL automatically appends the Windows paths when you install a distro. I know some users want a pure Linux environment but the majority of users like having the interoperability. So technically this is a bug.

**Comment by crramirez** [comment] 2019-04-12 17:17
Ok, I was misunderstood.

WSL automatically appends the Windows paths but only to the user that is logged when the console is open. Any other user that you invoke using sudo -s or su - will lose the environment and the Windows Paths.

So, not having Windows path in root when you invoke it using sudo -s is not an issue is how it works.
